# Setup
title:               ''
tagline:             ''
description:         'bio/ health x data/ AI <br/> <a href="https://twitter.com/tfarrell01">@tfarrell01</a>'
url:                 https://tmfarrell.github.io
paginate:            5
permalink:           pretty
markdown:            kramdown

# About/contact
author:
  name:              ''
  url:               https://twitter.com/tfarrell01
  email:             tfarrell01@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
