# Setup
title:               Tim Farrell
tagline:             bio/ health &nbsp; x &nbsp; data/ AI
description:         bio/ health &nbsp; x &nbsp; data/ AI
url:                 https://tmfarrell.github.io
baseurl:             ''
# paginate: 5  # Using show-more pattern; uncomment for index pagination
permalink:           pretty
markdown:            kramdown

# Theme
remote_theme:        riggraz/no-style-please

# Theme config (no-style-please)
theme_config:
  appearance:        "light"
  back_home_text:    ".."
  date_format:       "%Y-%m"
  show_description:  false
  lowercase_titles:  false

# About/contact
author:
  name:              Tim Farrell
  url:               https://twitter.com/tfarrell01
  email:             tfarrell01@gmail.com

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom vars
version:             1.0.0

exclude: [
  "docs/", ".well-known/", ".github/",  "indexer/", ".claude/", ".cursor/", "scripts/",
   ".env", "README.md", "LICENSE.md", "Makefile", "_data/talks.yaml", "_data/analyses.yaml", 
   "tmfarrell-github-io.conda_env.yml", "opencode.json",  "token.json"
]
